# Settings
TITLE = "Pong"
WIDTH = 1000
HEIGHT = 680
FPS = 60
FONT_NAME = "helvetica"

# Player properties
PLAYER_ACC = 0.5
PLAYER_FRICTION = -0.12
PLAYER_HEIGHT = 20
PLAYER_WIDTH = 80

# Ball properties
BALL_SPEED = 0.7

# Powerup properties
POWERUP_SPEED = 2
POWERUP_SPAWN_CHANCE = 80

# Brick properties
BRICK_WIDTH = 100
BRICK_HEIGHT = 40
BRICK_PLACEMENT = [(0, BRICK_HEIGHT), (BRICK_WIDTH+1, BRICK_HEIGHT), (BRICK_WIDTH*2+2, BRICK_HEIGHT), (BRICK_WIDTH*3+3, BRICK_HEIGHT),
                   (BRICK_WIDTH*4+4, BRICK_HEIGHT), (BRICK_WIDTH*5+5, BRICK_HEIGHT), (BRICK_WIDTH*6+6, BRICK_HEIGHT), (BRICK_WIDTH*7+7, BRICK_HEIGHT),
                   (BRICK_WIDTH*8+8, BRICK_HEIGHT), (BRICK_WIDTH*9+9, BRICK_HEIGHT), (0, BRICK_HEIGHT*2+1), (BRICK_WIDTH+1, BRICK_HEIGHT*2+1),
                   (BRICK_WIDTH*2+2, BRICK_HEIGHT*2+1), (BRICK_WIDTH*3+3, BRICK_HEIGHT*2+1), (BRICK_WIDTH*4+4, BRICK_HEIGHT*2+1), (BRICK_WIDTH*5+5, BRICK_HEIGHT*2+1),
                   (BRICK_WIDTH*6+6, BRICK_HEIGHT*2+1), (BRICK_WIDTH*7+7, BRICK_HEIGHT*2+1), (BRICK_WIDTH*8+8, BRICK_HEIGHT*2+1), (BRICK_WIDTH*9+9, BRICK_HEIGHT*2+1)]

# define colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
YELLOW = (255, 255, 0)